/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterPlannerRouteImport } from './routes/water-planner'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PestAlertRouteImport } from './routes/pest-alert'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as CropPlanningRouteImport } from './routes/crop-planning'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WaterPlannerRoute = WaterPlannerRouteImport.update({
  id: '/water-planner',
  path: '/water-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PestAlertRoute = PestAlertRouteImport.update({
  id: '/pest-alert',
  path: '/pest-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const CropPlanningRoute = CropPlanningRouteImport.update({
  id: '/crop-planning',
  path: '/crop-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crop-planning': typeof CropPlanningRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/pest-alert': typeof PestAlertRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/water-planner': typeof WaterPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crop-planning': typeof CropPlanningRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/pest-alert': typeof PestAlertRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/water-planner': typeof WaterPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crop-planning': typeof CropPlanningRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/pest-alert': typeof PestAlertRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/water-planner': typeof WaterPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crop-planning'
    | '/harvest'
    | '/home'
    | '/login'
    | '/market'
    | '/pest-alert'
    | '/profile'
    | '/signup'
    | '/water-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/crop-planning'
    | '/harvest'
    | '/home'
    | '/login'
    | '/market'
    | '/pest-alert'
    | '/profile'
    | '/signup'
    | '/water-planner'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crop-planning'
    | '/harvest'
    | '/home'
    | '/login'
    | '/market'
    | '/pest-alert'
    | '/profile'
    | '/signup'
    | '/water-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CropPlanningRoute: typeof CropPlanningRoute
  HarvestRoute: typeof HarvestRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  PestAlertRoute: typeof PestAlertRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  WaterPlannerRoute: typeof WaterPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/water-planner': {
      id: '/water-planner'
      path: '/water-planner'
      fullPath: '/water-planner'
      preLoaderRoute: typeof WaterPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-alert': {
      id: '/pest-alert'
      path: '/pest-alert'
      fullPath: '/pest-alert'
      preLoaderRoute: typeof PestAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-planning': {
      id: '/crop-planning'
      path: '/crop-planning'
      fullPath: '/crop-planning'
      preLoaderRoute: typeof CropPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CropPlanningRoute: CropPlanningRoute,
  HarvestRoute: HarvestRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  PestAlertRoute: PestAlertRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  WaterPlannerRoute: WaterPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
